"""add webpush_subscription

Revision ID: 3c6c699b2124
Revises: bc9c56914bb0
Create Date: 2025-12-15 12:36:17.815193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6c699b2124'
down_revision = 'bc9c56914bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=256), nullable=False),
    sa.Column('auth', sa.String(length=128), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('webpush_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webpush_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webpush_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webpush_subscription_user_id'))

    op.drop_table('webpush_subscription')
    # ### end Alembic commands ###
