"""add talker models

Revision ID: 3cb81a4e1269
Revises: 174ef049e65a
Create Date: 2025-12-14 16:07:58.657210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cb81a4e1269'
down_revision = '174ef049e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talk_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talk_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['talk_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talk_room_members',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['talk_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.drop_table('teams_events')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('start_event',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_event',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=550),
               nullable=False)
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'team', ['event_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'event_category', ['event_category_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('variants',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=600),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('post_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('stripe_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('product_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index('idx_sponsors_kind')
        batch_op.drop_index('idx_sponsors_kind_orderz')
        batch_op.drop_index('idx_sponsors_orderz')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('main_league',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('confirm',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    with op.batch_alter_table('variant_products', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('confirmed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('confirm',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('main_league',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index('idx_sponsors_orderz', ['orderz'], unique=False)
        batch_op.create_index('idx_sponsors_kind_orderz', ['kind', 'orderz'], unique=False)
        batch_op.create_index('idx_sponsors_kind', ['kind'], unique=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('product_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('stripe_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('post_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=600),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('variants',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('event_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=550),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('end_event',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_event',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('teams_events',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='teams_events_event_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='teams_events_team_id_fkey')
    )
    op.drop_table('talk_room_members')
    op.drop_table('talk_message')
    op.drop_table('talk_room')
    # ### end Alembic commands ###
