"""add slug to post

Revision ID: 8bd12657b446
Revises: 3e1efed09a19
Create Date: 2025-12-29 12:14:05.305548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd12657b446'
down_revision = '3e1efed09a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
