"""initial

Revision ID: b59c3b439ca6
Revises: 7e260c24948d
Create Date: 2025-12-17 23:48:56.736296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59c3b439ca6'
down_revision = '7e260c24948d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_lineups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_lineups_team_id'), ['team_id'], unique=False)

    op.create_table('team_lineup_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['team_lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineup_id', 'player_id', name='uq_lineup_player')
    )
    with op.batch_alter_table('team_lineup_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_lineup_slots_lineup_id'), ['lineup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_lineup_slots_player_id'), ['player_id'], unique=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=180),
               nullable=True)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('team_lineup_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_lineup_slots_player_id'))
        batch_op.drop_index(batch_op.f('ix_team_lineup_slots_lineup_id'))

    op.drop_table('team_lineup_slots')
    with op.batch_alter_table('team_lineups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_lineups_team_id'))

    op.drop_table('team_lineups')
    # ### end Alembic commands ###
