"""add talker + push

Revision ID: bc9c56914bb0
Revises: 3cb81a4e1269
Create Date: 2025-12-14 16:40:33.009009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9c56914bb0'
down_revision = '3cb81a4e1269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('push_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_token_user_id'))

    op.drop_table('push_token')
    # ### end Alembic commands ###
