"""Initial migration

Revision ID: d5392c3a6729
Revises: 
Create Date: 2023-10-31 22:34:58.470301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5392c3a6729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams_events')
    op.drop_table('product_sizes')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('start_event',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_event',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=550),
               nullable=False)
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'team', ['event_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'event_category', ['event_category_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('stripe_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('product_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('main_league',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirm',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('variant_products', schema=None) as batch_op:
        batch_op.drop_constraint('variant_products_size_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_products_size_id_fkey', 'product_sizes', ['variant_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirm',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('main_league',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('product_gallery', schema=None) as batch_op:
        batch_op.alter_column('image_file2',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('stripe_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('event_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=550),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('end_event',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_event',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('product_sizes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_sizes_pkey')
    )
    op.create_table('teams_events',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='teams_events_event_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='teams_events_team_id_fkey')
    )
    # ### end Alembic commands ###
